version: '3.8'

services:
  backend:
    build: ./musicprompt-backend
    env_file:
      - ./.env
    container_name: musicprompt-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/musicprompt
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: musicprompt-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: musicprompt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: musicprompt-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: